const API='https://script.google.com/macros/s/AKfycbz1T6sCG8U2txL7oH9mZeUaGhqFjzHlS0Aym9WRHTguhQ5UpPKngEUn4DcxxkQvK96dlA/exec';
const ZENDESK_TICKET_URL='https://admision.zendesk.com/agent/tickets/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let generation=0;
function cancelled(g){return g!==generation;}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();}
async function getState(){return (await chrome.storage.local.get('ticketAnalysis')).ticketAnalysis||{};}
async function patch(p){const old=await getState();const next={...old,...p};await chrome.storage.local.set({ticketAnalysis:next});chrome.runtime.sendMessage({type:'STATE_UPDATED',state:next}).catch(()=>{});return next;}
async function queryExisting(){const r=await fetch(`${API}?action=existing&t=${Date.now()}`,{cache:'no-store',redirect:'follow'});const j=await r.json();if(!j.ok)throw new Error(j.message||'No se pudo consultar BASE_TICKETS');return j;}
function normalizeType(v){const x=norm(v);if(x.includes('REEVALU'))return'REEVALUADO';if(x.includes('REASIGN'))return'REASIGNADO';return'NUEVO';}
function detailState(a){const d=norm(a?.detalle);if(d==='EN REVISION')return'EN_ATENCION';if(d==='EN ESPERA')return'EN_ESPERA';if(d==='PENDIENTE')return'PENDIENTE';if(d==='SEGUIMIENTO')return'SEGUIMIENTO';if(d==='DERIVADO')return'DERIVADO';if(d==='ATENDIDO')return'ATENDIDO';if(d==='CERRADO')return'CERRADO';if(!d)return'SIN_DETALLE';return'OTRO';}
function analyzeAgainstBase(row,base){const dni=String(row.dni||'');const id=String(row.idTicket||'');const a=dni?base.dniAnalysis?.[dni]:null;const exact=base.ticketRows?.[id]||null;const exists=Boolean(exact)||(base.tickets||[]).map(String).includes(id);const antecedent=a?.antecedente||exact||null;const total=Number(a?.totalRegistros||base.dniHistory?.[dni]?.length||0);const has=Boolean(antecedent)||total>0;let tipo=normalizeType(a?.tipoTicket||antecedent?.tipoTicket||exact?.tipoTicket);
  if(!has&&!exists)tipo='NUEVO';
  else if(!exists&&has&&String(antecedent?.idTicket||'')!==id)tipo='REEVALUADO';
  else{const s=detailState(antecedent);if(s==='ATENDIDO'&&(antecedent?.fechaFinTieneValor||antecedent?.fechaFin))tipo='REEVALUADO';else if(['SEGUIMIENTO','PENDIENTE','DERIVADO','CERRADO','OTRO'].includes(s))tipo='REASIGNADO';}
  let origen='REVISAR';const platform=String(row.platform||row.fuente||'ZENDESK').toUpperCase();
  if(platform==='DYNAMIC')origen='DYNAMIC';
  else if(has)origen='ZENDESK';
  else origen=['PORTAL','ZENDESK'].includes(String(row.origen||'').toUpperCase())?String(row.origen).toUpperCase():'REVISAR';
  const enriched={...row,idTicket:id,dni,ticketExists:exists,hasAntecedent:has,totalRegistros:total,antecedente,tipoTicket:tipo,origen,platform,detalleActual:exact?.detalle||antecedent?.detalle||'',fechaInicioBase:exact?.fechaInicio||antecedent?.fechaInicio||a?.fechaInicio||'',ticketAnterior:antecedent?.idTicket||''};
  return computeStatus(enriched);
}
function canRegister(row){const s=detailState(row.antecedente);if(['EN_ATENCION','EN_ESPERA'].includes(s))return false;if(!row.ticketExists)return true;if(['SEGUIMIENTO','PENDIENTE','DERIVADO','CERRADO','OTRO'].includes(s))return true;if(s==='ATENDIDO')return Boolean(row.antecedente?.fechaFinTieneValor||row.antecedente?.fechaFin);return false;}
function computeStatus(row){if(!row.dni)return{...row,status:'REVISAR_DNI',selected:false,allowReimport:false};const s=detailState(row.antecedente);if(s==='EN_ATENCION')return{...row,status:'EN_ATENCION',selected:false,allowReimport:false};if(s==='EN_ESPERA')return{...row,status:'EN_ESPERA',selected:false,allowReimport:false};if(!['PORTAL','ZENDESK','DYNAMIC'].includes(String(row.origen||'').toUpperCase()))return{...row,status:'REVISAR_ORIGEN',selected:false,allowReimport:false};if(canRegister(row))return{...row,status:'LISTO',selected:row.selected??true,allowReimport:Boolean(row.ticketExists)};if(row.ticketExists)return{...row,status:'EN_BASE',selected:false,allowReimport:false};return{...row,status:'LISTO',selected:true,allowReimport:false};}
async function waitTab(tabId,timeout=45000){const start=Date.now();while(Date.now()-start<timeout){try{const t=await chrome.tabs.get(tabId);if(t.status==='complete'){await sleep(1800);return;}}catch(_){}await sleep(500);}throw new Error('Tiempo agotado al abrir el ticket');}
async function readZendeskTicket(tabId){for(let i=0;i<7;i++){try{const r=await chrome.tabs.sendMessage(tabId,{type:'EXTRACT_TICKET'});if(r?.ok)return r.data;}catch(_){}await sleep(900);}throw new Error('No se pudo leer el ticket de Zendesk');}
async function analyzeZendesk(items,g){const base=await queryExisting();let rows=items.map(x=>({...x,platform:'ZENDESK',status:'VERIFICANDO',selected:false}));await patch({active:true,phase:'analysis',source:'ZENDESK',total:rows.length,processed:0,results:rows,error:''});for(let i=0;i<rows.length;i++){if(cancelled(g))return;let row=analyzeAgainstBase(rows[i],base);if(!row.hasAntecedent&&!['PORTAL','ZENDESK'].includes(String(row.origen||''))){let tab;try{tab=await chrome.tabs.create({url:ZENDESK_TICKET_URL+encodeURIComponent(row.idTicket),active:false});await waitTab(tab.id);const inside=await readZendeskTicket(tab.id);row=analyzeAgainstBase({...row,...inside,platform:'ZENDESK'},base);}catch(e){row={...row,status:'ERROR',selected:false,message:e.message};}finally{if(tab?.id)chrome.tabs.remove(tab.id).catch(()=>{});}}
    rows[i]=row;await patch({processed:i+1,results:rows});await sleep(120);}await patch({active:false,phase:'ready',results:rows,finishedAt:new Date().toISOString()});}
async function analyzeDynamic(items,tabId,g){const base=await queryExisting();let rows=items.map(x=>({...x,platform:'DYNAMIC',origen:'DYNAMIC',status:'VERIFICANDO',selected:false}));await patch({active:true,phase:'dynamic_dni',source:'DYNAMIC',total:rows.length,processed:0,results:rows,error:''});for(let i=0;i<rows.length;i++){if(cancelled(g))return;let row=analyzeAgainstBase(rows[i],base);if(!row.dni&&!row.ticketExists){try{const r=await chrome.tabs.sendMessage(tabId,{type:'READ_DYNAMIC_CASE_BY_ID',idTicket:row.idTicket});if(r?.ok&&r.data)row=analyzeAgainstBase({...row,...r.data,platform:'DYNAMIC',origen:'DYNAMIC'},base);else row={...row,status:'REVISAR_DNI',selected:false,message:r?.message||'No se pudo obtener Nro. documento'};}catch(e){row={...row,status:'REVISAR_DNI',selected:false,message:e.message};}}
    rows[i]=row;await patch({processed:i+1,results:rows});await sleep(180);}await patch({active:false,phase:'ready',results:rows,finishedAt:new Date().toISOString()});}
async function importItems(items){const g=generation;let state=await getState(),rows=state.results||[];await patch({active:true,phase:'import',importTotal:items.length,imported:0});let imported=0;for(const item of items){if(cancelled(g))break;const correctionMode=String(item.correctionMode||'REEVALUADO').toUpperCase();const action=correctionMode==='OBSERVADO'?'reopenObserved':'import';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,correctionMode,detalleNuevo:correctionMode==='OBSERVADO'?'En revisión':undefined,permitirReingreso:Boolean(item.allowReimport),...item}),redirect:'follow'});const j=await r.json();const idx=rows.findIndex(x=>String(x.idTicket)===String(item.idTicket));if(idx>=0){if(j.ok){rows[idx]={...rows[idx],imported:true,status:'PENDIENTE',selected:false,detalleActual:j.detalleNuevo||'En revisión',message:j.message||'Registrado'};imported++;}else rows[idx]={...rows[idx],status:j.ticketDuplicate?'EN_BASE':'ERROR_IMPORTACION',selected:false,message:j.message||'Error al importar'};}await patch({results:rows,imported});}catch(e){const idx=rows.findIndex(x=>String(x.idTicket)===String(item.idTicket));if(idx>=0)rows[idx]={...rows[idx],status:'ERROR_IMPORTACION',selected:false,message:e.message};await patch({results:rows,imported});}}
  await patch({active:false,phase:'ready',results:rows,imported});}
async function syncSeguimiento(items){const payload=(items||[]).map((x,i)=>({ticket:String(x.idTicket||''),dni:String(x.dni||''),order:i+1})).filter(x=>x.ticket);const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'syncSeguimiento',items:payload}),redirect:'follow'});const j=await r.json();if(!j.ok)throw new Error(j.message||'No se pudo actualizar Seguimiento');return j;}
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='START_ZENDESK'){const g=++generation;send({ok:true});analyzeZendesk(m.items||[],g).catch(e=>patch({active:false,phase:'error',error:e.message}));return true;}if(m?.type==='START_DYNAMIC'){const g=++generation;send({ok:true});analyzeDynamic(m.items||[],m.tabId,g).catch(e=>patch({active:false,phase:'error',error:e.message}));return true;}if(m?.type==='SAVE_SELECTION'){getState().then(s=>{const ids=new Set((m.ids||[]).map(String));const results=(s.results||[]).map(r=>({...r,selected:ids.has(String(r.idTicket))}));return patch({results});}).then(()=>send({ok:true}));return true;}if(m?.type==='UPDATE_ORIGIN'){getState().then(s=>{const results=(s.results||[]).map(r=>String(r.idTicket)===String(m.idTicket)?computeStatus({...r,origen:m.origen,origenManual:true}):r);return patch({results});}).then(()=>send({ok:true}));return true;}if(m?.type==='IMPORT_SELECTED'){send({ok:true});importItems(m.items||[]);return true;}if(m?.type==='SYNC_SEGUIMIENTO'){syncSeguimiento(m.items||[]).then(j=>send({ok:true,...j})).catch(e=>send({ok:false,message:e.message}));return true;}if(m?.type==='CANCEL_PROCESS'){generation++;patch({active:false,phase:'cancelled',cancelled:true,error:''}).then(()=>send({ok:true}));return true;}if(m?.type==='CLEAR'){chrome.storage.local.remove('ticketAnalysis').then(()=>send({ok:true}));return true;}if(m?.type==='GET_STATE'){getState().then(state=>send({ok:true,state}));return true;}});
