const API='https://script.google.com/macros/s/AKfycbz1T6sCG8U2txL7oH9mZeUaGhqFjzHlS0Aym9WRHTguhQ5UpPKngEUn4DcxxkQvK96dlA/exec';
const ZENDESK_TICKET_URL='https://admision.zendesk.com/agent/tickets/';
const AUTO_ALARM_NAME='UTP_TICKETS_AUTOPROCESO';
const AUTO_STORAGE_KEY='autoProcessConfig';
const AUTO_ALLOWED_INTERVALS=[1,5,10,15,30,60];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let generation=0;
function cancelled(g){return g!==generation;}
function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();}
async function getState(){return (await chrome.storage.local.get('ticketAnalysis')).ticketAnalysis||{};}
async function patch(p){const old=await getState();const next={...old,...p};await chrome.storage.local.set({ticketAnalysis:next});chrome.runtime.sendMessage({type:'STATE_UPDATED',state:next}).catch(()=>{});return next;}
async function waitWhilePaused(g){while(true){if(cancelled(g))return false;const s=await getState();if(!s.active||!s.paused)return true;await sleep(400);}}
async function queryExisting(){const r=await fetch(`${API}?action=existing&t=${Date.now()}`,{cache:'no-store',redirect:'follow'});const j=await r.json();if(!j.ok)throw new Error(j.message||'No se pudo consultar BASE_TICKETS');if(!Array.isArray(j.tickets)||!j.dniAnalysis)throw new Error('Apps Script no devolvió tickets y dniAnalysis');return j;}
function normalizeType(v){const x=norm(v);if(x.includes('REEVALU'))return'REEVALUADO';if(x.includes('REASIGN'))return'REASIGNADO';return'NUEVO';}
function detailState(a){const d=norm(a?.detalle);if(d==='EN REVISION')return'EN_ATENCION';if(d==='EN ESPERA')return'EN_ESPERA';if(d==='PENDIENTE')return'PENDIENTE';if(d==='SEGUIMIENTO')return'SEGUIMIENTO';if(d==='DERIVADO')return'DERIVADO';if(d==='ATENDIDO')return'ATENDIDO';if(d==='CERRADO')return'CERRADO';if(!d)return'SIN_DETALLE';return'OTRO';}
function canRegister(row){const s=detailState(row.antecedente);if(['EN_ATENCION','EN_ESPERA'].includes(s))return false;if(!row.ticketExists)return true;if(['SEGUIMIENTO','PENDIENTE','DERIVADO','CERRADO','OTRO'].includes(s))return true;if(s==='ATENDIDO')return Boolean(row.antecedente?.fechaFinTieneValor||row.antecedente?.fechaFin);return false;}
function resolveType(row){const s=detailState(row.antecedente);const current=String(row.idTicket||'');const previous=String(row.antecedente?.idTicket||row.ticketAnterior||'');if(!row.ticketExists&&row.hasAntecedent&&(!previous||previous!==current))return'REEVALUADO';if(!row.ticketExists&&row.zendeskHasPreviousTickets)return'REEVALUADO';if(s==='ATENDIDO'&&(row.antecedente?.fechaFinTieneValor||row.antecedente?.fechaFin))return'REEVALUADO';if(['SEGUIMIENTO','PENDIENTE','DERIVADO','CERRADO','OTRO'].includes(s))return'REASIGNADO';if(s==='SIN_DETALLE'&&!row.hasAntecedent)return'NUEVO';return normalizeType(row.tipoTicket);}
function computeStatus(row){if(row.readError)return{...row,status:'ERROR',selected:false,allowReimport:false};if(!row.dni)return{...row,status:'REVISAR_DNI',selected:false,allowReimport:false};const s=detailState(row.antecedente);if(s==='EN_ATENCION')return{...row,tipoTicket:resolveType(row),status:'EN_ATENCION',selected:false,allowReimport:false,message:'El ticket ya está En revisión y no puede registrarse nuevamente'};if(s==='EN_ESPERA')return{...row,tipoTicket:resolveType(row),status:'EN_ESPERA',selected:false,allowReimport:false,message:'El ticket está En espera y queda bloqueado'};if(!['PORTAL','ZENDESK','DYNAMIC'].includes(String(row.origen||'').toUpperCase()))return{...row,tipoTicket:resolveType(row),status:'REVISAR_ORIGEN',selected:false,allowReimport:false};if(row.imported)return{...row,tipoTicket:resolveType(row),status:'PENDIENTE',selected:false,allowReimport:false};if(canRegister(row))return{...row,tipoTicket:resolveType(row),status:'LISTO',selected:row.selected??true,allowReimport:Boolean(row.ticketExists),message:row.ticketExists?'EN BASE - habilitado según detalle':row.message};if(row.ticketExists)return{...row,tipoTicket:resolveType(row),status:'EN_BASE',selected:false,allowReimport:false,message:'EN BASE'};return{...row,tipoTicket:resolveType(row),status:'LISTO',selected:true,allowReimport:false};}
function analyzeAgainstBase(row,base){let dni=String(row.dni||'');const id=String(row.idTicket||'');const exact=base.ticketRows?.[id]||null;if(!dni&&exact?.dni)dni=String(exact.dni);const a=dni?base.dniAnalysis?.[dni]:null;const exists=Boolean(exact)||(base.tickets||[]).map(String).includes(id);const antecedent=a?.antecedente||exact||null;const total=Number(a?.totalRegistros||base.dniHistory?.[dni]?.length||0);const has=Boolean(antecedent)||total>0;const platform=String(row.platform||row.fuente||'ZENDESK').toUpperCase();let origen='REVISAR';if(platform==='DYNAMIC')origen='DYNAMIC';else if(has)origen='ZENDESK';else origen=['PORTAL','ZENDESK'].includes(String(row.origen||'').toUpperCase())?String(row.origen).toUpperCase():'REVISAR';if(row.origenManual&&platform!=='DYNAMIC'&&!has)origen=['PORTAL','ZENDESK'].includes(String(row.origen||'').toUpperCase())?String(row.origen).toUpperCase():'REVISAR';const enriched={...row,idTicket:id,dni,ticketExists:exists,hasAntecedent:has,totalRegistros:total,antecedente,tipoTicket:normalizeType(a?.tipoTicket||antecedent?.tipoTicket||exact?.tipoTicket),origen,platform,detalleActual:exact?.detalle||antecedent?.detalle||'',fechaInicioBase:exact?.fechaInicio||antecedent?.fechaInicio||a?.fechaInicio||'',responsableAnterior:antecedent?.responsable||'',ticketAnterior:antecedent?.idTicket||'',previousTickets:base.dniTickets?.[dni]||[]};return computeStatus({...enriched,tipoTicket:resolveType(enriched)});}
async function waitTab(tabId,timeout=45000){const start=Date.now();while(Date.now()-start<timeout){try{const t=await chrome.tabs.get(tabId);if(t.status==='complete'){await sleep(1800);return;}}catch(_){}await sleep(500);}throw new Error('Tiempo agotado al abrir el ticket');}
async function readZendeskTicket(tabId){for(let i=0;i<7;i++){try{const r=await chrome.tabs.sendMessage(tabId,{type:'EXTRACT_TICKET'});if(r?.ok)return r.data;}catch(_){}await sleep(900);}throw new Error('No se pudo leer el ticket de Zendesk');}
async function zendeskHistory(id){try{const t=await fetch(`https://admision.zendesk.com/api/v2/tickets/${encodeURIComponent(id)}.json`,{credentials:'include',cache:'no-store'}).then(r=>r.json());const requester=t?.ticket?.requester_id;if(!requester)return{checked:true,hasPrevious:false,previousTickets:[]};const h=await fetch(`https://admision.zendesk.com/api/v2/users/${requester}/tickets/requested.json?sort_by=created_at&sort_order=desc`,{credentials:'include',cache:'no-store'}).then(r=>r.json());const previous=(h?.tickets||[]).filter(x=>String(x.id)!==String(id)).map(x=>({idTicket:String(x.id),status:x.status,createdAt:x.created_at,updatedAt:x.updated_at,subject:x.subject}));return{checked:true,hasPrevious:previous.length>0,previousTickets:previous};}catch(e){return{checked:false,hasPrevious:false,previousTickets:[],error:e.message};}}
async function analyzeZendesk(items,g){const base=await queryExisting();let rows=items.map(x=>({...x,idTicket:String(x.idTicket||''),platform:'ZENDESK',status:'VERIFICANDO',selected:false}));await patch({active:true,paused:false,phase:'checking',source:'ZENDESK',total:rows.length,processed:0,results:rows,error:'',cancelled:false});for(let i=0;i<rows.length;i++){if(cancelled(g))return;if(!(await waitWhilePaused(g)))return;let row=analyzeAgainstBase(rows[i],base);if(row.dni&&!row.hasAntecedent){const h=await zendeskHistory(row.idTicket);row=analyzeAgainstBase({...row,zendeskHistoryChecked:h.checked,zendeskHasPreviousTickets:h.hasPrevious,zendeskPreviousTickets:h.previousTickets},base);}if(!row.hasAntecedent&&!['PORTAL','ZENDESK'].includes(String(row.origen||''))){let tab;try{tab=await chrome.tabs.create({url:ZENDESK_TICKET_URL+encodeURIComponent(row.idTicket),active:false});await waitTab(tab.id);const inside=await readZendeskTicket(tab.id);row=analyzeAgainstBase({...row,...inside,platform:'ZENDESK'},base);}catch(e){row={...row,status:'ERROR',selected:false,message:e.message};}finally{if(tab?.id)chrome.tabs.remove(tab.id).catch(()=>{});}}rows[i]=row;await patch({phase:'analysis',processed:i+1,results:rows});await sleep(100);}await patch({active:false,paused:false,phase:'ready',results:rows,finishedAt:new Date().toISOString()});}
async function analyzeDynamic(items,tabId,g){const base=await queryExisting();let rows=items.map(x=>({...x,idTicket:String(x.idTicket||''),platform:'DYNAMIC',origen:'DYNAMIC',status:'VERIFICANDO',selected:false}));await patch({active:true,paused:false,phase:'checking',source:'DYNAMIC',total:rows.length,processed:0,results:rows,error:'',cancelled:false});for(let i=0;i<rows.length;i++){if(cancelled(g))return;if(!(await waitWhilePaused(g)))return;let row=analyzeAgainstBase(rows[i],base);if(!row.dni&&!row.ticketExists){try{const r=await chrome.tabs.sendMessage(tabId,{type:'READ_DYNAMIC_CASE_BY_ID',idTicket:row.idTicket});if(r?.ok&&r.data)row=analyzeAgainstBase({...row,...r.data,platform:'DYNAMIC',origen:'DYNAMIC'},base);else row={...row,status:'REVISAR_DNI',selected:false,message:r?.message||'No se pudo obtener Nro. documento'};}catch(e){row={...row,status:'REVISAR_DNI',selected:false,message:e.message};}}rows[i]=row;await patch({phase:'analysis',processed:i+1,results:rows});await sleep(150);}await patch({active:false,paused:false,phase:'ready',results:rows,finishedAt:new Date().toISOString()});}
async function importItems(items,options={}){const g=generation;const before=await getState();const keepPaused=Boolean(options.whilePaused&&before.active&&before.paused);let rows=before.results||[];await patch({active:true,paused:keepPaused,phase:'import',importTotal:items.length,imported:0});let imported=0;for(const item of items){if(cancelled(g))break;const correctionMode=String(item.correctionMode||'REEVALUADO').toUpperCase();const action=correctionMode==='OBSERVADO'?'reopenObserved':'import';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,correctionMode,detalleNuevo:correctionMode==='OBSERVADO'?'En revisión':undefined,permitirReingreso:Boolean(item.allowReimport),...item}),redirect:'follow'});const j=await r.json();const idx=rows.findIndex(x=>String(x.idTicket)===String(item.idTicket));if(idx>=0){if(j.ok){rows[idx]={...rows[idx],imported:true,status:'PENDIENTE',selected:false,detalleActual:j.detalleNuevo||'En revisión',tipoTicket:normalizeType(j.tipoTicket||rows[idx].tipoTicket),message:j.message||'Registrado'};imported++;}else if(j.ticketDuplicate)rows[idx]={...rows[idx],ticketExists:true,status:'EN_BASE',selected:false,message:j.message||'EN BASE'};else rows[idx]={...rows[idx],status:'ERROR_IMPORTACION',selected:false,message:j.message||'Error al importar'};}await patch({results:rows,imported});}catch(e){const idx=rows.findIndex(x=>String(x.idTicket)===String(item.idTicket));if(idx>=0)rows[idx]={...rows[idx],status:'ERROR_IMPORTACION',selected:false,message:e.message};await patch({results:rows,imported});}}await patch({active:keepPaused,paused:keepPaused,phase:keepPaused?(before.phase||'analysis'):'ready',results:rows,imported});}
async function syncSeguimiento(items){const payload=(items||[]).map((x,i)=>({ticket:String(x.idTicket||''),dni:String(x.dni||''),order:i+1})).filter(x=>x.ticket);const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'syncSeguimiento',items:payload}),redirect:'follow'});const j=await r.json();if(!j.ok)throw new Error(j.message||'No se pudo actualizar Seguimiento');await patch({followupMessage:j.message||'Seguimiento actualizado',followupSaved:j.saved??payload.length,followupUpdated:j.updated??0});return j;}
async function getAutoConfig(){const s=(await chrome.storage.local.get(AUTO_STORAGE_KEY))[AUTO_STORAGE_KEY]||{};const interval=AUTO_ALLOWED_INTERVALS.includes(Number(s.interval))?Number(s.interval):5;return{enabled:Boolean(s.enabled),interval,running:Boolean(s.running),lastRun:s.lastRun||'',nextRun:s.nextRun||'',lastResult:s.lastResult||'Autoproceso detenido',lastError:s.lastError||''};}
async function patchAuto(p){const n={...(await getAutoConfig()),...p};await chrome.storage.local.set({[AUTO_STORAGE_KEY]:n});chrome.runtime.sendMessage({type:'AUTO_STATE_UPDATED',config:n}).catch(()=>{});return n;}
async function configureAuto(enabled,interval){const safe=AUTO_ALLOWED_INTERVALS.includes(Number(interval))?Number(interval):5;await chrome.alarms.clear(AUTO_ALARM_NAME);if(enabled)chrome.alarms.create(AUTO_ALARM_NAME,{delayInMinutes:safe,periodInMinutes:safe});const alarm=enabled?await chrome.alarms.get(AUTO_ALARM_NAME):null;return patchAuto({enabled:Boolean(enabled),interval:safe,running:false,nextRun:alarm?.scheduledTime?new Date(alarm.scheduledTime).toISOString():'',lastResult:enabled?`Autoproceso activo cada ${safe} minuto(s)`:'Autoproceso detenido',lastError:''});}
async function findZendeskTab(){const tabs=await chrome.tabs.query({url:'https://admision.zendesk.com/agent/filters/*'});return tabs[0]||null;}
async function extractZendeskRows(tabId){for(let i=0;i<8;i++){try{const r=await chrome.tabs.sendMessage(tabId,{type:'EXTRACT_VIEW_ROWS'});if(r?.ok&&Array.isArray(r.items))return r;}catch(_){}await sleep(800);}throw new Error('No se pudo leer la vista de Zendesk');}
function autoCandidate(r){return r.status==='LISTO'&&!r.ticketExists&&Boolean(r.dni)&&['PORTAL','ZENDESK'].includes(String(r.origen||'').toUpperCase())&&['NUEVO','REEVALUADO'].includes(normalizeType(r.tipoTicket));}
async function runAuto(trigger='alarm'){const cfg=await getAutoConfig();if(cfg.running)return{ok:false,skipped:true,message:'Ya existe un ciclo automático en ejecución'};if(trigger==='alarm'&&!cfg.enabled)return{ok:false,skipped:true,message:'Autoproceso desactivado'};await patchAuto({running:true,lastResult:'1/4 Preparando Seguimiento...',lastError:''});try{const tab=await findZendeskTab();if(!tab?.id)throw new Error('No se encontró abierta la vista de filtros de Zendesk');await chrome.tabs.reload(tab.id);await waitTab(tab.id,50000);const scan=await extractZendeskRows(tab.id);const items=(scan.items||[]).filter(x=>x.idTicket).map(x=>({...x,idTicket:String(x.idTicket),platform:'ZENDESK'}));if(!items.length)throw new Error('Zendesk no devolvió tickets válidos');await patchAuto({lastResult:`1/4 Ejecutando Seguimiento para ${items.length} ticket(s)...`});await syncSeguimiento(items);await patchAuto({lastResult:`2/4 Analizando ${items.length} ticket(s)...`});const g=++generation;await analyzeZendesk(items,g);let state=await getState();const selected=(state.results||[]).filter(autoCandidate);await patchAuto({lastResult:`3/4 ${selected.length} ticket(s) listos para importar...`});if(selected.length){await patchAuto({lastResult:`4/4 Importando ${selected.length} ticket(s)...`});await importItems(selected.map(x=>({...x,selected:true})));}const done=`Ciclo completo: ${items.length} analizados y ${selected.length} candidato(s) procesados.`;const alarm=cfg.enabled?await chrome.alarms.get(AUTO_ALARM_NAME):null;await patchAuto({running:false,lastRun:new Date().toISOString(),nextRun:alarm?.scheduledTime?new Date(alarm.scheduledTime).toISOString():'',lastResult:done,lastError:''});return{ok:true,message:done};}catch(e){await patchAuto({running:false,lastRun:new Date().toISOString(),lastResult:`Error: ${e.message}`,lastError:e.message});return{ok:false,message:e.message};}}
chrome.runtime.onConnect.addListener(port=>{if(port.name==='UTP_ANALYSIS_KEEPALIVE')port.onMessage.addListener(m=>{if(m?.type==='PING')port.postMessage({type:'PONG',at:Date.now()});});});
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='START_ZENDESK'){const g=++generation;send({ok:true});analyzeZendesk(m.items||[],g).catch(e=>patch({active:false,phase:'error',error:e.message}));return true;}if(m?.type==='START_DYNAMIC'){const g=++generation;send({ok:true});analyzeDynamic(m.items||[],m.tabId,g).catch(e=>patch({active:false,phase:'error',error:e.message}));return true;}if(m?.type==='TOGGLE_PAUSE'){getState().then(s=>patch({paused:s.active?!s.paused:false})).then(s=>send({ok:true,paused:s.paused}));return true;}if(m?.type==='SAVE_SELECTION'){getState().then(s=>{const ids=new Set((m.ids||[]).map(String));return patch({results:(s.results||[]).map(r=>({...r,selected:ids.has(String(r.idTicket))}))});}).then(()=>send({ok:true}));return true;}if(m?.type==='UPDATE_ORIGIN'){getState().then(s=>patch({results:(s.results||[]).map(r=>String(r.idTicket)===String(m.idTicket)?computeStatus({...r,origen:m.origen,origenManual:true}):r)})).then(()=>send({ok:true}));return true;}if(m?.type==='UPDATE_CORRECTION_MODE'){getState().then(s=>patch({results:(s.results||[]).map(r=>String(r.idTicket)===String(m.idTicket)?{...r,correctionMode:String(m.correctionMode||'REEVALUADO').toUpperCase()}:r)})).then(()=>send({ok:true}));return true;}if(m?.type==='IMPORT_SELECTED'){send({ok:true,total:(m.items||[]).length});importItems(m.items||[],{whilePaused:Boolean(m.whilePaused)});return true;}if(m?.type==='SYNC_SEGUIMIENTO'){syncSeguimiento(m.items||[]).then(j=>send({ok:true,...j})).catch(e=>send({ok:false,message:e.message}));return true;}if(m?.type==='CANCEL_PROCESS'){generation++;Promise.all([patch({active:false,paused:false,phase:'cancelled',cancelled:true,error:''}),patchAuto({running:false,lastResult:'Proceso cancelado por el usuario'})]).then(()=>send({ok:true}));return true;}if(m?.type==='CLEAR'){chrome.storage.local.remove('ticketAnalysis').then(()=>send({ok:true}));return true;}if(m?.type==='GET_STATE'){getState().then(state=>send({ok:true,state}));return true;}if(m?.type==='AUTO_GET_CONFIG'){Promise.all([getAutoConfig(),chrome.alarms.get(AUTO_ALARM_NAME)]).then(([config,alarm])=>send({ok:true,config:{...config,nextRun:alarm?.scheduledTime?new Date(alarm.scheduledTime).toISOString():config.nextRun}}));return true;}if(m?.type==='AUTO_CONFIGURE'){configureAuto(Boolean(m.enabled),Number(m.interval)).then(config=>send({ok:true,config})).catch(e=>send({ok:false,message:e.message}));return true;}if(m?.type==='AUTO_RUN_NOW'){runAuto('manual').then(send);return true;}});
chrome.alarms.onAlarm.addListener(a=>{if(a.name===AUTO_ALARM_NAME)runAuto('alarm');});
chrome.runtime.onInstalled.addListener(async()=>{const c=await getAutoConfig();if(c.enabled)await configureAuto(true,c.interval);});
chrome.runtime.onStartup.addListener(async()=>{const c=await getAutoConfig();if(c.enabled)await configureAuto(true,c.interval);});