function dNorm(value=''){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();}
const dSleep=ms=>new Promise(r=>setTimeout(r,ms));
function parseDynamicTitle(text){const raw=dNorm(text);const m=raw.match(/^(CAS-[A-Z0-9-]+)\s*-\s*(U\d+)\s*-?\s*(.+)$/i);if(!m)return null;return{idTicket:`${m[1].toUpperCase()} - ${m[2].toUpperCase()}`,alumno:dNorm(m[3]),tituloOriginal:raw};}
function caseLinkFromRow(row){const a=row?.querySelector?.('a[href]');return a?.href||'';}
function rowForDynamicId(idTicket){const wanted=dNorm(idTicket).toUpperCase();return [...document.querySelectorAll('[role="row"],.ag-row,tr')].find(row=>dNorm(row.innerText||row.textContent||'').toUpperCase().includes(wanted))||null;}
function visibleDynamicRows(){const out=new Map();const rows=[...document.querySelectorAll('[role="row"],.ag-row,tr')];for(const row of rows){const text=dNorm(row.innerText||row.textContent||'');const match=text.match(/CAS-[A-Z0-9-]+\s*-\s*U\d+[^\n]*/i);if(!match)continue;const parsed=parseDynamicTitle(match[0]);if(!parsed)continue;const link=caseLinkFromRow(row);out.set(parsed.idTicket,{...parsed,url:link,origen:'DYNAMIC',platform:'DYNAMIC'});}return[...out.values()];}
function findDynamicScroller(){return [...document.querySelectorAll('*')].filter(e=>{const s=getComputedStyle(e);return/(auto|scroll)/.test(s.overflowY)&&e.scrollHeight>e.clientHeight+100;}).map(e=>({e,score:(e.querySelectorAll('.ag-row,[role="row"]').length*1000)+e.clientHeight})).sort((a,b)=>b.score-a.score)[0]?.e||document.scrollingElement;}
async function extractDynamicView(){const map=new Map();const scroller=findDynamicScroller();const start=scroller?.scrollTop||0;if(scroller)scroller.scrollTop=0;let last=-1,stable=0;for(let i=0;i<120;i++){visibleDynamicRows().forEach(r=>map.set(r.idTicket,{...(map.get(r.idTicket)||{}),...r}));if(!scroller)break;const next=Math.min(scroller.scrollTop+Math.max(450,scroller.clientHeight*.8),scroller.scrollHeight);scroller.scrollTop=next;await dSleep(220);stable=scroller.scrollTop===last?stable+1:0;last=scroller.scrollTop;if(stable>=3||scroller.scrollTop+scroller.clientHeight>=scroller.scrollHeight-4)break;}if(scroller)scroller.scrollTop=start;return{items:[...map.values()],count:map.size};}
function valueNearLabelDynamic(labelText){const wanted=dNorm(labelText).toLowerCase();for(const el of [...document.querySelectorAll('label,span,div,p')]){const t=dNorm(el.textContent).toLowerCase();if(!(t===wanted||t.startsWith(wanted)))continue;const forId=el.getAttribute('for');if(forId){const input=document.getElementById(forId);const v=input?.value||input?.textContent;if(dNorm(v))return dNorm(v);}let c=el;for(let i=0;i<5&&c;i++,c=c.parentElement){const input=c.querySelector?.('input,textarea,[role="textbox"],[role="combobox"]');const v=input?.value||input?.getAttribute?.('value')||input?.textContent;if(dNorm(v)&&dNorm(v).toLowerCase()!==t)return dNorm(v);const texts=[...c.querySelectorAll?.('span,div')||[]].map(x=>dNorm(x.textContent)).filter(Boolean);const candidate=texts.find(v=>v.toLowerCase()!==t&&/\d{4,20}/.test(v));if(candidate)return candidate;}}return '';}
function extractDynamicDetail(){const body=dNorm(document.body?.innerText||'');const titleMatch=body.match(/CAS-[A-Z0-9-]+\s*-\s*U\d+[^\n]*/i);const parsed=titleMatch?parseDynamicTitle(titleMatch[0]):null;let dni=valueNearLabelDynamic('Nro. documento');if(!dni)dni=body.match(/Nro\.\s*documento\s*[:\-]?\s*([0-9]{4,20})/i)?.[1]||'';dni=String(dni).replace(/[^0-9]/g,'');return{...(parsed||{}),dni,origen:'DYNAMIC',platform:'DYNAMIC'};}
async function waitForDetail(idTicket,timeout=25000){const started=Date.now();while(Date.now()-started<timeout){const body=dNorm(document.body?.innerText||'').toUpperCase();if(body.includes(dNorm(idTicket).toUpperCase())&&body.includes('NRO. DOCUMENTO')){await dSleep(800);return true;}await dSleep(450);}return false;}
async function waitForGrid(timeout=25000){const started=Date.now();while(Date.now()-started<timeout){if(document.querySelector('.ag-row,[role="row"]')&&/Mis casos activos|Titulo de caso|Título de caso/i.test(document.body?.innerText||'')){await dSleep(700);return true;}await dSleep(450);}return false;}
async function readDynamicCaseById(idTicket){let row=rowForDynamicId(idTicket);if(!row){const scroller=findDynamicScroller();if(scroller)scroller.scrollTop=0;for(let i=0;i<120&&!row;i++){row=rowForDynamicId(idTicket);if(row)break;if(!scroller)break;scroller.scrollTop=Math.min(scroller.scrollTop+Math.max(450,scroller.clientHeight*.8),scroller.scrollHeight);await dSleep(180);}}if(!row)throw new Error('No se encontro el caso en la grilla de DYNAMIC');const link=row.querySelector('a[href]');const clickable=link||[...row.querySelectorAll('[role="gridcell"],td,div,span')].find(e=>dNorm(e.textContent).toUpperCase().includes(dNorm(idTicket).toUpperCase()))||row;const before=location.href;clickable.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));if(!(await waitForDetail(idTicket)))throw new Error('El caso no abrio el detalle con Nro. documento');const data=extractDynamicDetail();if(!data.dni)throw new Error('No se encontro Nro. documento');history.back();await waitForGrid();return data;}
chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type==='EXTRACT_DYNAMIC_VIEW'){extractDynamicView().then(r=>sendResponse({ok:true,...r})).catch(e=>sendResponse({ok:false,message:e.message}));return true;}if(message?.type==='EXTRACT_DYNAMIC_DETAIL'){try{sendResponse({ok:true,data:extractDynamicDetail()});}catch(e){sendResponse({ok:false,message:e.message});}return true;}if(message?.type==='READ_DYNAMIC_CASE_BY_ID'){readDynamicCaseById(message.idTicket).then(data=>sendResponse({ok:true,data})).catch(e=>sendResponse({ok:false,message:e.message}));return true;}});
