function norm(value=''){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const pageText=()=>document.body?.innerText||'';
function valueByLabel(labels){const wanted=labels.map(v=>norm(v).toLowerCase());for(const el of [...document.querySelectorAll('label,span,div,p')]){const t=norm(el.textContent).toLowerCase();if(!wanted.some(v=>t===v||t.startsWith(v)))continue;const forId=el.getAttribute('for');if(forId){const input=document.getElementById(forId);const value=input?.value||input?.textContent;if(norm(value))return norm(value);}let c=el;for(let i=0;i<4&&c;i++,c=c.parentElement){const input=c.querySelector?.('input,textarea,[role="combobox"],[contenteditable="true"]');const value=input?.value||input?.getAttribute?.('value')||input?.textContent;if(norm(value)&&norm(value).toLowerCase()!==t)return norm(value);}}return '';}
function cleanDocumentNumber(value){const digits=String(value??'').replace(/[^0-9]/g,'');return digits.length>=4&&digits.length<=20?digits:'';}
function getTicketId(){return location.pathname.match(/\/tickets\/(\d+)/)?.[1]||pageText().match(/(?:Incidente|Ticket)\s*#?(\d+)/i)?.[1]||'';}
function getDni(){return cleanDocumentNumber(valueByLabel(['DNI','DNI*']))||cleanDocumentNumber(pageText().match(/\bDNI\s*\*?\s*[:\-]?\s*([0-9][0-9 .-]{2,24})/i)?.[1]||'');}
function getAlumno(){return valueByLabel(['Apellidos y Nombres','Apellidos y Nombres*'])||norm(pageText().match(/Apellidos y Nombres\s*\*?\s*[:\-]?\s*([^\n]+)/i)?.[1]||'');}
function getCampus(){return valueByLabel(['Campus','Campus*'])||norm(pageText().match(/Sede de Estudio\s*:\s*([^\n•]+)/i)?.[1]||'');}
function getTipoIngreso(){return valueByLabel(['Modalidad de ingreso','Modalidad de ingreso*'])||norm(pageText().match(/Modalidad(?: de ingreso)?\s*:\s*([^\n•]+)/i)?.[1]||'');}
async function detectOrigin(){const selectors=['section[role="feed"][data-test-id="omni-log-container"]','section[role="feed"][data-testid="omni-log-container"]','[role="feed"][data-test-id="omni-log-container"]','[role="feed"][data-testid="omni-log-container"]'];const found=[];for(const s of selectors)document.querySelectorAll(s).forEach(e=>{if(!found.includes(e))found.push(e);});if(!found.length)return{origen:'REVISAR',origenDetectado:false,motivoOrigen:'No se encontro el historial de Zendesk'};for(const c of found){try{c.scrollTop=c.scrollHeight;await sleep(250);for(let i=0;i<16;i++){c.scrollTop=0;await sleep(180);}c.scrollTop=c.scrollHeight;}catch(_){}}const text=norm(found.map(c=>c.innerText||c.textContent||'').join(' ')).toUpperCase();return{origen:/\bPORTAL\b/.test(text)?'PORTAL':'ZENDESK',origenDetectado:true,motivoOrigen:/\bPORTAL\b/.test(text)?'Se detecto PORTAL en el historial':'No se detecto PORTAL'};}
function parseViewDate(value){const raw=norm(value);if(!raw)return{iso:'',text:''};const now=new Date();const out=new Date(now);out.setSeconds(0,0);const tm=raw.match(/(\d{1,2}):(\d{2})/);const h=tm?Number(tm[1]):12,m=tm?Number(tm[2]):0;const low=norm(raw).toLowerCase();if(low.startsWith('hoy'))out.setHours(h,m,0,0);else if(low.startsWith('ayer')){out.setDate(out.getDate()-1);out.setHours(h,m,0,0);}else{const map={domingo:0,lunes:1,martes:2,miercoles:3,jueves:4,viernes:5,sabado:6};const day=Object.keys(map).find(k=>low.startsWith(k));if(day){let d=(out.getDay()-map[day]+7)%7;if(d===0)d=7;out.setDate(out.getDate()-d);out.setHours(h,m,0,0);}else{return{iso:'',text:raw};}}return{iso:out.toISOString(),text:`${String(out.getDate()).padStart(2,'0')}/${String(out.getMonth()+1).padStart(2,'0')}/${out.getFullYear()}`};}
async function extractTicket(){const originInfo=await detectOrigin();return{idTicket:getTicketId(),dni:getDni(),alumno:getAlumno(),campus:getCampus(),tipoConvalidacion:'Expediente',tipoIngreso:getTipoIngreso(),...originInfo,observacion:''};}
function getViewRows(){const map=new Map();document.querySelectorAll('a[href*="/agent/tickets/"]').forEach(a=>{const id=a.href.match(/\/agent\/tickets\/(\d+)/)?.[1];if(!id)return;const row=a.closest('tr,[role="row"]');const lines=String(row?.innerText||'').split(/\n+/).map(norm).filter(Boolean);let dni=lines.map(cleanDocumentNumber).find(v=>v&&v!==id)||'';let alumno='';if(dni){const i=lines.indexOf(dni);alumno=lines[i+1]||'';}const dateCandidate=lines.find(v=>/^(hoy|ayer|lunes|martes|miercoles|jueves|viernes|sabado|domingo)/i.test(norm(v)));const parsed=parseViewDate(dateCandidate||'');map.set(id,{idTicket:id,dni,alumno,fechaInicio:parsed.iso,fechaInicioTexto:parsed.text,origen:'REVISAR'});});return[...map.values()];}
async function allViewRows(){const map=new Map();let scroller=[...document.querySelectorAll('*')].filter(e=>{const s=getComputedStyle(e);return/(auto|scroll)/.test(s.overflowY)&&e.scrollHeight>e.clientHeight+80;}).sort((a,b)=>(b.querySelectorAll('a[href*="/agent/tickets/"]').length)-(a.querySelectorAll('a[href*="/agent/tickets/"]').length))[0]||document.scrollingElement;const start=scroller?.scrollTop||0;if(scroller)scroller.scrollTop=0;let stable=0,last=-1;for(let i=0;i<80;i++){getViewRows().forEach(x=>map.set(x.idTicket,{...(map.get(x.idTicket)||{}),...x}));if(!scroller)break;scroller.scrollTop=Math.min(scroller.scrollTop+Math.max(450,scroller.clientHeight*.82),scroller.scrollHeight);await sleep(250);stable=scroller.scrollTop===last?stable+1:0;last=scroller.scrollTop;if(stable>=2||scroller.scrollTop+scroller.clientHeight>=scroller.scrollHeight-4)break;}if(scroller)scroller.scrollTop=start;return{items:[...map.values()],pagesRead:1,expected:map.size};}
chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type==='EXTRACT_TICKET'){extractTicket().then(data=>sendResponse({ok:true,data})).catch(e=>sendResponse({ok:false,message:e.message}));return true;}if(message?.type==='EXTRACT_VIEW_ROWS'){allViewRows().then(r=>sendResponse({ok:true,...r})).catch(e=>sendResponse({ok:false,message:e.message}));return true;}});
