const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let platform='ZENDESK',current={};
const AUTH_USERS={ADMIN1:{name:'Administrador 1',role:'ADMIN'},ADMIN2:{name:'Administrador 2',role:'ADMIN'},INVITADO1:{name:'Invitado 1',role:'INVITADO'},INVITADO2:{name:'Invitado 2',role:'INVITADO'}};let authSession=null;
async function sha256(text){const bytes=new TextEncoder().encode(String(text||''));const hash=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function initAuth(){const d=await chrome.storage.local.get(['utpAuthConfig','utpAuthSession']);if(d.utpAuthSession&&AUTH_USERS[d.utpAuthSession.user]){authSession={...AUTH_USERS[d.utpAuthSession.user],user:d.utpAuthSession.user};showSession();}}
function showSession(){$('authOverlay')?.classList.add('hidden');$('userBar')?.classList.remove('hidden');$('sessionName').textContent=authSession?.name||'-';$('sessionRole').textContent=authSession?.role==='ADMIN'?'Administrador':'Invitado';}
$('authLogin').onclick=async()=>{const user=$('authUser').value,password=$('authPassword').value;const d=await chrome.storage.local.get('utpAuthConfig');const config=d.utpAuthConfig||null;if(!config?.passwordHash){if(user!=='ADMIN1'){return $('authError').textContent='La primera configuración debe realizarla Administrador 1.';}if(password.length<6)return $('authError').textContent='Usa una contraseña de al menos 6 caracteres.';await chrome.storage.local.set({utpAuthConfig:{passwordHash:await sha256(password),changedAt:Date.now()}});}else if(await sha256(password)!==config.passwordHash)return $('authError').textContent='Contraseña incorrecta.';authSession={...AUTH_USERS[user],user};await chrome.storage.local.set({utpAuthSession:{user,loginAt:Date.now()}});showSession();};
$('logout').onclick=async()=>{await chrome.storage.local.remove('utpAuthSession');location.reload();};
function setPlatform(value){platform=value;$('tabZendesk').classList.toggle('active',value==='ZENDESK');$('tabDynamic').classList.toggle('active',value==='DYNAMIC');$('analyze').textContent=value==='ZENDESK'?'1. Analizar Zendesk':'1. Analizar DYNAMIC';$('message').textContent=value==='ZENDESK'?'Abre la vista de filtros de Zendesk y pulsa Analizar.':'Abre Mis casos activos en DYNAMIC y pulsa Analizar.';}
$('tabZendesk').onclick=()=>setPlatform('ZENDESK');$('tabDynamic').onclick=()=>setPlatform('DYNAMIC');
function validOrigin(row){return['PORTAL','ZENDESK','DYNAMIC'].includes(String(row?.origen||'').toUpperCase());}
function selectable(row){return Boolean(row?.dni)&&row.status==='LISTO'&&validOrigin(row);}
function originOptions(row){const allowed=row.platform==='DYNAMIC'?['DYNAMIC']:row.hasAntecedent?['ZENDESK']:['PORTAL','ZENDESK','REVISAR'];return allowed.map(v=>`<option value="${v}" ${String(row.origen).toUpperCase()===v?'selected':''}>${v}</option>`).join('');}
function typeLabel(row){if(row.ticketExists||row.imported)return`REGISTRADO - ${row.tipoTicket||'NUEVO'}`;if(row.tipoTicket==='REEVALUADO')return'NUEVO - REEVALUADO';return row.tipoTicket||'NUEVO';}
function render(state={}){current=state;const rows=state.results||[];$('total').textContent=state.total||rows.length;$('new').textContent=rows.filter(r=>r.tipoTicket==='NUEVO').length;$('reassigned').textContent=rows.filter(r=>r.tipoTicket==='REASIGNADO').length;$('reevaluated').textContent=rows.filter(r=>r.tipoTicket==='REEVALUADO').length;$('attention').textContent=rows.filter(r=>r.status==='EN_ATENCION').length;$('waiting').textContent=rows.filter(r=>r.status==='EN_ESPERA').length;const total=state.total||0,done=state.processed||0;$('bar').style.width=total?`${Math.round(done*100/total)}%`:'0%';
 if(state.active)$('message').textContent=state.source==='DYNAMIC'?`DYNAMIC: obteniendo DNI y clasificando ${done} de ${total}.`:`Zendesk: clasificando ${done} de ${total}.`;else if(state.error)$('message').textContent=`Error: ${state.error}`;else if(state.cancelled)$('message').textContent='Proceso cancelado.';else if(rows.length)$('message').textContent=`Análisis listo: ${rows.length} ticket(s).`;
 $('rows').innerHTML=rows.map(r=>`<tr><td><input class="pick" data-id="${esc(r.idTicket)}" type="checkbox" ${r.selected?'checked':''} ${selectable(r)?'':'disabled'}></td><td><b>${esc(r.idTicket)}</b>${r.ticketAnterior?`<div class="small">Anterior: ${esc(r.ticketAnterior)}</div>`:''}</td><td>${esc(r.dni||'-')}</td><td>${esc(r.alumno||'-')}</td><td><span class="source ${esc(r.platform||'')}">${esc(r.platform||'-')}</span></td><td><span class="type ${esc(r.tipoTicket||'')}">${esc(typeLabel(r))}</span></td><td><select class="origin" data-id="${esc(r.idTicket)}" ${r.platform==='DYNAMIC'?'disabled':''}>${originOptions(r)}</select></td><td><span class="tag ${esc(r.status||'')}">${esc(r.status||'-')}</span>${r.message?`<div class="small">${esc(r.message)}</div>`:''}</td></tr>`).join('');document.querySelectorAll('.pick').forEach(x=>x.onchange=saveSelection);document.querySelectorAll('.origin').forEach(x=>x.onchange=async e=>{await chrome.runtime.sendMessage({type:'UPDATE_ORIGIN',idTicket:e.target.dataset.id,origen:e.target.value});});}
async function saveSelection(){const ids=[...document.querySelectorAll('.pick:checked')].map(x=>x.dataset.id);await chrome.runtime.sendMessage({type:'SAVE_SELECTION',ids});}
async function getActiveTab(){return(await chrome.tabs.query({active:true,currentWindow:true}))[0];}
$('analyze').onclick=async()=>{try{const tab=await getActiveTab();if(platform==='ZENDESK'){if(!tab?.url?.includes('admision.zendesk.com/agent/filters/'))throw new Error('Abre primero la vista de filtros de Zendesk.');$('message').textContent='Leyendo Zendesk...';const r=await chrome.tabs.sendMessage(tab.id,{type:'EXTRACT_VIEW_ROWS'});if(!r?.ok||!r.items?.length)throw new Error(r?.message||'No se encontraron tickets en Zendesk');await chrome.runtime.sendMessage({type:'START_ZENDESK',items:r.items});}else{if(!tab?.url?.includes('crm2.dynamics.com'))throw new Error('Abre primero Mis casos activos en DYNAMIC.');$('message').textContent='Leyendo DYNAMIC...';const r=await chrome.tabs.sendMessage(tab.id,{type:'EXTRACT_DYNAMIC_VIEW'});if(!r?.ok||!r.items?.length)throw new Error(r?.message||'No se encontraron casos en DYNAMIC');await chrome.runtime.sendMessage({type:'START_DYNAMIC',items:r.items,tabId:tab.id});}}catch(e){$('message').textContent=e.message;}};
$('selectReady').onclick=async()=>{const ids=(current.results||[]).filter(selectable).map(r=>String(r.idTicket));await chrome.runtime.sendMessage({type:'SAVE_SELECTION',ids});};$('clearSel').onclick=()=>chrome.runtime.sendMessage({type:'SAVE_SELECTION',ids:[]});$('master').onchange=async e=>{const ids=e.target.checked?(current.results||[]).filter(selectable).map(r=>String(r.idTicket)):[];await chrome.runtime.sendMessage({type:'SAVE_SELECTION',ids});};
$('import').onclick=async()=>{const items=(current.results||[]).filter(r=>r.selected&&selectable(r)).map(r=>({...r,usuarioExtension:authSession?.name||'',codigoUsuarioExtension:authSession?.user||'',rolExtension:authSession?.role||'',fechaOperacionExtension:new Date().toISOString()}));if(!items.length)return $('message').textContent='No hay tickets LISTO seleccionados.';await chrome.runtime.sendMessage({type:'IMPORT_SELECTED',items});};
$('followup').onclick=async()=>{const items=current.results||[];if(!items.length)return $('message').textContent='Primero analiza una bandeja.';const r=await chrome.runtime.sendMessage({type:'SYNC_SEGUIMIENTO',items});$('message').textContent=r?.ok?(r.message||'Seguimiento actualizado'):(r?.message||'No se pudo actualizar Seguimiento');};$('cancelProcess').onclick=()=>chrome.runtime.sendMessage({type:'CANCEL_PROCESS'});$('clear').onclick=async()=>{await chrome.runtime.sendMessage({type:'CLEAR'});render({});};
$('openFull')?.addEventListener('click',()=>chrome.tabs.create({url:chrome.runtime.getURL('full.html')}));chrome.runtime.onMessage.addListener(m=>{if(m?.type==='STATE_UPDATED')render(m.state);});async function load(){const r=await chrome.runtime.sendMessage({type:'GET_STATE'});if(r?.ok)render(r.state||{});}initAuth();load();setInterval(load,3000);
